export const mockInfluencers = [
  {
    id: 1,
    name: "Sarah Johnson",
    username: "@sarahjohnson",
    followers: 125000,
    engagement: 4.2,
    niche: "Fashion",
    location: "New York",
    avatar: "/placeholder.svg?height=40&width=40",
    verified: true,
    rate: 2500,
  },
  {
    id: 2,
    name: "Mike Chen",
    username: "@mikechen",
    followers: 89000,
    engagement: 5.1,
    niche: "Tech",
    location: "San Francisco",
    avatar: "/placeholder.svg?height=40&width=40",
    verified: false,
    rate: 1800,
  },
  {
    id: 3,
    name: "Emma Davis",
    username: "@emmadavis",
    followers: 203000,
    engagement: 3.8,
    niche: "Lifestyle",
    location: "Los Angeles",
    avatar: "/placeholder.svg?height=40&width=40",
    verified: true,
    rate: 3200,
  },
]

export const mockCampaigns = [
  {
    id: 1,
    name: "Summer Fashion Launch",
    status: "Active",
    budget: 15000,
    spent: 8500,
    reach: 450000,
    engagement: 18500,
    influencers: 5,
    startDate: "2024-06-01",
    endDate: "2024-07-31",
  },
  {
    id: 2,
    name: "Tech Product Review",
    status: "Completed",
    budget: 8000,
    spent: 7800,
    reach: 280000,
    engagement: 12300,
    influencers: 3,
    startDate: "2024-05-15",
    endDate: "2024-06-15",
  },
  {
    id: 3,
    name: "Holiday Collection",
    status: "Draft",
    budget: 25000,
    spent: 0,
    reach: 0,
    engagement: 0,
    influencers: 0,
    startDate: "2024-11-01",
    endDate: "2024-12-31",
  },
]

export const mockProjects = [
  {
    id: 1,
    name: "E-commerce Platform",
    client: "TechCorp Inc.",
    status: "In Progress",
    progress: 65,
    startDate: "2024-03-01",
    deadline: "2024-08-15",
    budget: 45000,
    team: ["John Doe", "Jane Smith", "Mike Johnson"],
  },
  {
    id: 2,
    name: "Mobile Banking App",
    client: "FinanceFirst",
    status: "Testing",
    progress: 90,
    startDate: "2024-01-15",
    deadline: "2024-06-30",
    budget: 65000,
    team: ["Sarah Wilson", "Tom Brown", "Lisa Chen"],
  },
  {
    id: 3,
    name: "CRM System",
    client: "SalesMax",
    status: "Planning",
    progress: 15,
    startDate: "2024-07-01",
    deadline: "2024-12-15",
    budget: 35000,
    team: ["Alex Turner", "Emma Davis"],
  },
]

export const mockTasks = [
  {
    id: 1,
    title: "Design user authentication flow",
    description: "Create wireframes and mockups for login/signup process",
    status: "To Do",
    priority: "High",
    assignee: "John Doe",
    dueDate: "2024-07-15",
    project: "E-commerce Platform",
  },
  {
    id: 2,
    title: "Implement payment gateway",
    description: "Integrate Stripe payment processing",
    status: "In Progress",
    priority: "High",
    assignee: "Jane Smith",
    dueDate: "2024-07-20",
    project: "E-commerce Platform",
  },
  {
    id: 3,
    title: "Write API documentation",
    description: "Document all REST endpoints",
    status: "Done",
    priority: "Medium",
    assignee: "Mike Johnson",
    dueDate: "2024-07-10",
    project: "Mobile Banking App",
  },
]

export const mockUsers = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    role: "Brand Manager",
    status: "Active",
    joinDate: "2024-01-15",
    lastLogin: "2024-07-10",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah@example.com",
    role: "Influencer",
    status: "Active",
    joinDate: "2024-02-20",
    lastLogin: "2024-07-09",
  },
  {
    id: 3,
    name: "Mike Chen",
    email: "mike@porchest.com",
    role: "Employee",
    status: "Active",
    joinDate: "2024-01-01",
    lastLogin: "2024-07-10",
  },
]

export const mockAnalytics = {
  totalUsers: 1247,
  activeUsers: 892,
  totalCampaigns: 156,
  activeCampaigns: 23,
  totalRevenue: 245000,
  monthlyGrowth: 12.5,
  engagementRate: 4.2,
  conversionRate: 2.8,
}

export const mockData = {
  brand: {
    campaigns: [
      {
        id: 1,
        name: "Summer Fashion Launch",
        status: "active",
        budget: 15000,
        spent: 8500,
        reach: 450000,
        engagement: 18500,
        influencers: 5,
        startDate: "2024-06-01",
        endDate: "2024-07-31",
        roi: 285,
      },
      {
        id: 2,
        name: "Tech Product Review",
        status: "completed",
        budget: 8000,
        spent: 7800,
        reach: 280000,
        engagement: 12300,
        influencers: 3,
        startDate: "2024-05-15",
        endDate: "2024-06-15",
        roi: 320,
      },
      {
        id: 3,
        name: "Holiday Collection",
        status: "draft",
        budget: 25000,
        spent: 0,
        reach: 0,
        engagement: 0,
        influencers: 0,
        startDate: "2024-11-01",
        endDate: "2024-12-31",
        roi: 0,
      },
    ],
    influencers: mockInfluencers,
    analytics: {
      totalCampaigns: 156,
      activeCampaigns: 23,
      totalSpent: 245000,
      avgROI: 285,
      totalReach: 2400000,
      totalEngagement: 98500,
    },
  },

  influencer: {
    profile: {
      name: "Sarah Johnson",
      username: "@sarahjohnson",
      followers: 125000,
      engagement: 4.2,
      niche: "Fashion",
      location: "New York",
      verified: true,
      totalEarnings: 45000,
      completedCampaigns: 28,
    },
    collaborations: [
      {
        id: 1,
        brand: "Fashion Forward",
        campaign: "Summer Collection",
        status: "pending",
        offer: 2500,
        deadline: "2024-07-20",
        requirements: "3 Instagram posts, 1 story series",
      },
      {
        id: 2,
        brand: "TechGear",
        campaign: "Product Launch",
        status: "accepted",
        offer: 1800,
        deadline: "2024-07-15",
        requirements: "1 YouTube review, 2 Instagram posts",
      },
      {
        id: 3,
        brand: "Lifestyle Co",
        campaign: "Brand Partnership",
        status: "completed",
        offer: 3200,
        deadline: "2024-06-30",
        requirements: "4 Instagram posts, 1 blog post",
      },
    ],
    earnings: {
      thisMonth: 8500,
      lastMonth: 6200,
      totalEarnings: 45000,
      pendingPayments: 4300,
    },
  },

  client: {
    projects: [
      {
        id: 1,
        name: "E-commerce Platform",
        status: "in-progress",
        progress: 65,
        startDate: "2024-03-01",
        deadline: "2024-08-15",
        budget: 45000,
        team: ["John Doe", "Jane Smith", "Mike Johnson"],
      },
      {
        id: 2,
        name: "Mobile Banking App",
        status: "testing",
        progress: 90,
        startDate: "2024-01-15",
        deadline: "2024-06-30",
        budget: 65000,
        team: ["Sarah Wilson", "Tom Brown", "Lisa Chen"],
      },
      {
        id: 3,
        name: "CRM System",
        status: "planning",
        progress: 15,
        startDate: "2024-07-01",
        deadline: "2024-12-15",
        budget: 35000,
        team: ["Alex Turner", "Emma Davis"],
      },
    ],
    deliverables: [
      {
        id: 1,
        project: "E-commerce Platform",
        milestone: "User Authentication",
        status: "completed",
        dueDate: "2024-06-15",
        completedDate: "2024-06-12",
      },
      {
        id: 2,
        project: "E-commerce Platform",
        milestone: "Payment Integration",
        status: "in-progress",
        dueDate: "2024-07-20",
        completedDate: null,
      },
      {
        id: 3,
        project: "Mobile Banking App",
        milestone: "Security Audit",
        status: "pending",
        dueDate: "2024-07-25",
        completedDate: null,
      },
    ],
    messages: [
      {
        id: 1,
        sender: "Project Manager",
        message: "The authentication module has been completed and is ready for review.",
        time: "2 hours ago",
        project: "E-commerce Platform",
      },
      {
        id: 2,
        sender: "Developer",
        message: "Payment gateway integration is 80% complete. Testing phase will begin tomorrow.",
        time: "5 hours ago",
        project: "E-commerce Platform",
      },
      {
        id: 3,
        sender: "QA Team",
        message: "Security audit scheduled for next week. Please prepare the documentation.",
        time: "1 day ago",
        project: "Mobile Banking App",
      },
    ],
  },

  employee: {
    recentTasks: [
      {
        id: 1,
        title: "Design user authentication flow",
        project: "E-commerce Platform",
        status: "in-progress",
        progress: 75,
        dueDate: "Jul 15",
      },
      {
        id: 2,
        title: "Implement payment gateway",
        project: "E-commerce Platform",
        status: "completed",
        progress: 100,
        dueDate: "Jul 10",
      },
      {
        id: 3,
        title: "Write API documentation",
        project: "Mobile Banking App",
        status: "pending",
        progress: 0,
        dueDate: "Jul 20",
      },
    ],
    teamUpdates: [
      {
        id: 1,
        author: "Project Manager",
        message: "Team meeting scheduled for tomorrow at 10 AM to discuss sprint planning.",
        time: "2 hours ago",
        type: "announcement",
      },
      {
        id: 2,
        author: "Sarah Wilson",
        message: "Completed the user interface mockups for the banking app. Ready for review.",
        time: "4 hours ago",
        type: "update",
      },
      {
        id: 3,
        author: "Tech Lead",
        message: "New coding standards document has been uploaded to the shared drive.",
        time: "1 day ago",
        type: "announcement",
      },
    ],
    kanbanTasks: [
      {
        id: 1,
        title: "Design user authentication flow",
        description: "Create wireframes and mockups for login/signup process",
        status: "todo",
        priority: "high",
        assignee: "John Doe",
        dueDate: "Jul 15",
        project: "E-commerce Platform",
      },
      {
        id: 2,
        title: "Implement payment gateway",
        description: "Integrate Stripe payment processing",
        status: "in-progress",
        priority: "high",
        assignee: "Jane Smith",
        dueDate: "Jul 20",
        project: "E-commerce Platform",
      },
      {
        id: 3,
        title: "Write API documentation",
        description: "Document all REST endpoints",
        status: "done",
        priority: "medium",
        assignee: "Mike Johnson",
        dueDate: "Jul 10",
        project: "Mobile Banking App",
      },
      {
        id: 4,
        title: "Setup CI/CD pipeline",
        description: "Configure automated deployment",
        status: "todo",
        priority: "medium",
        assignee: "Alex Turner",
        dueDate: "Jul 25",
        project: "CRM System",
      },
      {
        id: 5,
        title: "Database optimization",
        description: "Improve query performance",
        status: "in-progress",
        priority: "low",
        assignee: "Emma Davis",
        dueDate: "Jul 30",
        project: "E-commerce Platform",
      },
    ],
    chatChannels: [
      {
        id: 1,
        name: "General Team",
        lastMessage: "Great work on the authentication module!",
        lastMessageTime: "2 min ago",
        unreadCount: 2,
        members: 8,
        status: "online",
        messages: [
          {
            id: 1,
            sender: "John Doe",
            content: "Good morning team! Ready for today's sprint review?",
            time: "9:00 AM",
          },
          {
            id: 2,
            sender: "Jane Smith",
            content: "Yes! I've completed the payment integration testing.",
            time: "9:05 AM",
          },
          {
            id: 3,
            sender: "Mike Johnson",
            content: "Great work on the authentication module!",
            time: "9:10 AM",
          },
        ],
      },
      {
        id: 2,
        name: "Development Team",
        lastMessage: "Code review scheduled for 2 PM",
        lastMessageTime: "1 hour ago",
        unreadCount: 0,
        members: 5,
        status: "online",
        messages: [
          {
            id: 1,
            sender: "Tech Lead",
            content: "Please make sure all PRs are submitted by noon.",
            time: "8:30 AM",
          },
          {
            id: 2,
            sender: "Sarah Wilson",
            content: "Code review scheduled for 2 PM",
            time: "9:00 AM",
          },
        ],
      },
    ],
    reports: [
      {
        id: 1,
        title: "Weekly Status Report - Week 28",
        date: "Jul 8, 2024",
        status: "approved",
      },
      {
        id: 2,
        title: "Daily Report - Jul 9",
        date: "Jul 9, 2024",
        status: "pending",
      },
      {
        id: 3,
        title: "Project Milestone Report",
        date: "Jul 5, 2024",
        status: "approved",
      },
    ],
  },

  admin: {
    users: [
      {
        id: 1,
        name: "John Doe",
        email: "john@example.com",
        type: "brand",
        status: "active",
        joinedDate: "Jan 15, 2024",
        lastActive: "2 hours ago",
      },
      {
        id: 2,
        name: "Sarah Johnson",
        email: "sarah@example.com",
        type: "influencer",
        status: "active",
        joinedDate: "Feb 20, 2024",
        lastActive: "1 day ago",
      },
      {
        id: 3,
        name: "Mike Chen",
        email: "mike@porchest.com",
        type: "employee",
        status: "active",
        joinedDate: "Jan 1, 2024",
        lastActive: "Online",
      },
      {
        id: 4,
        name: "Emma Davis",
        email: "emma@client.com",
        type: "client",
        status: "pending",
        joinedDate: "Jul 1, 2024",
        lastActive: "3 days ago",
      },
      {
        id: 5,
        name: "Alex Turner",
        email: "alex@suspended.com",
        type: "influencer",
        status: "suspended",
        joinedDate: "Mar 10, 2024",
        lastActive: "1 week ago",
      },
    ],
    payments: [
      {
        id: 1,
        contractId: "CNT-2024-001",
        client: "TechCorp Inc.",
        service: "E-commerce Development",
        amount: 45000,
        status: "completed",
        date: "Jul 1, 2024",
      },
      {
        id: 2,
        contractId: "CNT-2024-002",
        client: "FinanceFirst",
        service: "Mobile App Development",
        amount: 65000,
        status: "pending",
        date: "Jul 5, 2024",
      },
      {
        id: 3,
        contractId: "CNT-2024-003",
        client: "SalesMax",
        service: "CRM System",
        amount: 35000,
        status: "failed",
        date: "Jul 3, 2024",
      },
    ],
    fraudAlerts: [
      {
        id: 1,
        type: "Suspicious Activity",
        user: "alex@suspicious.com",
        description: "Multiple failed login attempts from different IP addresses",
        severity: "high",
        status: "investigating",
        date: "Jul 10, 2024",
      },
      {
        id: 2,
        type: "Payment Fraud",
        user: "fake@user.com",
        description: "Attempted payment with stolen credit card information",
        severity: "high",
        status: "resolved",
        date: "Jul 8, 2024",
      },
      {
        id: 3,
        type: "Account Takeover",
        user: "victim@email.com",
        description: "Unusual account activity detected - password changed from new location",
        severity: "medium",
        status: "pending",
        date: "Jul 9, 2024",
      },
    ],
    recentAlerts: [
      {
        id: 1,
        message: "Server CPU usage above 85% threshold",
        severity: "high",
        time: "5 min ago",
      },
      {
        id: 2,
        message: "New user registration spike detected",
        severity: "medium",
        time: "1 hour ago",
      },
      {
        id: 3,
        message: "Database backup completed successfully",
        severity: "low",
        time: "2 hours ago",
      },
    ],
  },
}
